"""
Personalization Routes
API endpoints for financial assessment and personalization.
"""

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field
from typing import List, Optional
import logging

router = APIRouter(prefix="/api/v1/personalization", tags=["Personalization"])
logger = logging.getLogger(__name__)

from ..shared.financial_assessment import (
    assess_financial_health,
    DebtInput,
    UserContext,
    FinancialAssessmentResult,
    FinancialMetrics,
)
from ..shared.ai_service import get_ai_service


# ============================================================================
# Request/Response Models
# ============================================================================

class FinancialAssessmentRequest(BaseModel):
    """Request model for financial assessment"""
    profile_id: str = Field(..., description="User profile ID")
    debts: List[DebtInput] = Field(..., description="List of user's debts")
    user_context: UserContext = Field(..., description="User context for personalization")
    financial_metrics: Optional[FinancialMetrics] = Field(None, description="Financial metrics for comprehensive assessment")


# ============================================================================
# Routes
# ============================================================================

@router.post("/financial-assessment", response_model=FinancialAssessmentResult)
async def get_financial_assessment(request: FinancialAssessmentRequest):
    """
    Generate comprehensive financial health assessment.
    
    Note: This endpoint logs the incoming request for debugging purposes.
    
    This endpoint provides a complete debt composition risk analysis including:
    - Deterministic risk score (0-100)
    - Risk band classification
    - Financial interpretation with data-grounded insights
    - Personalized UX copy generated by AI
    
    **Example Request:**
    ```json
    {
      "profile_id": "user123",
      "debts": [
        {
          "balance": 10000.00,
          "apr": 24.99,
          "is_delinquent": false
        },
        {
          "balance": 5000.00,
          "apr": 21.50,
          "is_delinquent": true
        }
      ],
      "user_context": {
        "goal": "reduce_stress",
        "stress_level": "high",
        "employment_status": "stable",
        "life_events": "baby",
        "age_range": "35_44"
      }
    }
    ```
    
    **Example Response:**
    ```json
    {
      "assessment_version": "1.0.0",
      "generated_at": "2025-12-04T23:00:00Z",
      "deterministic_output": {
        "risk_score": 35.71,
        "risk_band": "moderate",
        "debt_count": 2,
        "primary_driver": "high_rate",
        "drivers": {
          "delinquency_factor": 0.50,
          "high_rate_factor": 1.00,
          "complexity_factor": 0.00
        },
        "driver_severity": ["high_rate", "delinquency", "complexity"]
      },
      "financial_interpretation": {
        "summary": "Your debt composition indicates multiple emerging risks...",
        "key_drivers": [
          "High Rate (100% impact)",
          "Delinquency (50% impact)"
        ],
        "interpretation_points": [
          "About 100% of your total debt carries interest rates ≥20%...",
          "1 of your 2 debts is currently delinquent..."
        ]
      },
      "personalized_ux": {
        "user_friendly_summary": "Your debt composition shows moderate risk...",
        "personalized_recommendations": [
          {
            "text": "Focus on paying down your highest-interest debts first...",
            "category": "interest_cost",
            "priority": 1,
            "action_id": "high-interest-focus"
          }
        ],
        "closing_message": "You're taking the right steps..."
      }
    }
    ```
    """
    try:
        # Log incoming request for debugging
        logger.info(f"Received financial assessment request for profile: {request.profile_id}")
        logger.info(f"Debts count: {len(request.debts)}")
        logger.info(f"User context: {request.user_context}")
        logger.info(f"Financial metrics: {request.financial_metrics}")
        
        # Validate that debts list is not empty
        if not request.debts:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="At least one debt is required for assessment"
            )
        
        # Get AI service for LLM integration
        try:
            ai_service = get_ai_service()
        except Exception as e:
            logger.warning(f"AI service not available, will use fallback UX copy: {e}")
            ai_service = None
        
        # Run assessment with financial metrics
        result = await assess_financial_health(
            debts=request.debts,
            user_context=request.user_context,
            financial_metrics=request.financial_metrics,
            ai_service=ai_service
        )
        
        return result
        
    except HTTPException:
        raise
    except ValueError as e:
        logger.error(f"Validation error in financial assessment: {e}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e)
        )
    except Exception as e:
        logger.error(f"Error generating financial assessment: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to generate financial assessment. Please try again."
        )